version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : leave_management_system
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  springboot:
    build: .
    container_name: leave-management
    environment:
      SERVER_PORT : 8081
      MYSQL_HOST : mysql
      MYSQL_PORT : 3306
      MYSQL_DB : leave_management_system
      MYSQL_USER : root
      MYSQL_PASSWORD : root
    ports:
      - "8082:8081"
    depends_on:
      - mysql


